### ISSUE TITLE
onColor and offColor transparent

### ISSUE THREAD

**Issue by brightsider** [markusenglund/react-switch#40]
Hello.
I set 'transparent' color for onColor and offColor. It's working but shows errors in console:
`Invalid prop 'onColor' supplied to 'ReactSwitch'. 'onColor' has to be either a 3-digit or 6-digit hex-color string. Valid examples: '#abc', '#123456'`

**Comment by markusenglund** [comment]
Yup, the component is not built to work with colors that are not hex-strings. You'll notice that if you put in any other color like "red", the color will still be transparent. That's is because the colors are re-computed to nonsensical hex-strings that the browser doesn't understand. (In the case of "transparent" the color is actually set to `#rraann` :smile: )

**Comment by brightsider** [comment]
@markusenglund wow, it’s unexpected :)
Maybe this should placed in readme?

**Comment by markusenglund** [comment]
It's there actually. Under the long API table so a bit hard notice.

**Comment by brightsider** [comment]
I don't see it in the documentation and even through the search

**Comment by markusenglund** [comment]
This is what I was referring to from the README:

> The following props have to be either 3-digit or 6-digit hex-colors: offColor, onColor, offHandleColor, and onHandleColor. This is because this library calculates intermediate color values based on the hex-color strings.

> Examples of valid colors: '#abc', '#123456'

> Examples of invalid colors: 'red', 'rgb(0,0,0)'
