### ISSUE TITLE
Add option to customize border-radius

### ISSUE THREAD

**Issue by lbraun** [markusenglund/react-switch#48]
Thank you for this package. Would it be possible to add a prop to customize the border radius, to allow for squarer switches, e.g. like this?:

![image](https://user-images.githubusercontent.com/294776/62630344-be91b400-b8fc-11e9-8f47-76de18df81a2.png)
![image](https://user-images.githubusercontent.com/294776/62630398-d5380b00-b8fc-11e9-8d02-290b6435086b.png)

Alternatively a more direct way to style the handle and background would be nice, i.e. what was proposed in #15 .

**Comment by markusenglund** [comment]
This seems like a cool thing to support.

As you say, we can either create a new `borderRadius` prop, or create a couple of style props for  the different html-tags. I played around a little bit to get a feel for the first option and made a PR for it here: #50 which probably won't get merged. The latter option is probably better long term because it adds more flexibility. I'll take a look at that soon.

**Comment by lbraun** [comment]
Awesome, thanks!

**Comment by markusenglund** [comment]
I ended up implementing the borderRadius property PR.
